name: license-key-manager
region: nyc

# Detect changes and auto-deploy from GitHub
services:
  - name: web
    # GitHub integration
    github:
      repo: yourusername/License_keys
      branch: main
      deploy_on_push: true

    # Build configuration
    build_command: npm run build
    
    # Run configuration
    run_command: npm start
    
    # Environment settings
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    
    # HTTP configuration
    http_port: 3000
    
    # Health check
    health_check:
      http_path: /
      initial_delay_seconds: 30
    
    # Environment variables (configure these in App Platform dashboard)
    envs:
      - key: NODE_ENV
        value: "production"
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: "${NEXT_PUBLIC_SUPABASE_URL}"
        type: SECRET
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: "${NEXT_PUBLIC_SUPABASE_ANON_KEY}"
        type: SECRET
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: "${SUPABASE_SERVICE_ROLE_KEY}"
        type: SECRET
      - key: EMAIL_WEBHOOK_URL
        value: "${EMAIL_WEBHOOK_URL}"
        type: SECRET
      - key: ADMIN_USERNAME
        value: "${ADMIN_USERNAME}"
        type: SECRET
      - key: ADMIN_PASSWORD
        value: "${ADMIN_PASSWORD}"
        type: SECRET
      - key: NEXT_PUBLIC_APP_URL
        value: "${APP_URL}"
      - key: FROM_EMAIL
        value: "noreply@yourdomain.com"

# Ingress configuration (handles routing and SSL)
ingress:
  rules:
    - component:
        name: web

